# Generated by Django 3.2.9 on 2022-05-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('Notes_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Notes_title', models.CharField(max_length=100)),
                ('Notes_file', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='Address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='Phone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
