# Generated by Django 3.2.9 on 2022-05-31 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_auto_20220530_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AddField(
            model_name='notes',
            name='Dept',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='info.dept'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='info.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='module',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='info.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='Notes_file',
            field=models.FileField(upload_to='notes'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='Notes_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
